---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable and start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy NGINX configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  
- name: Validating Nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0
  notify: Restart NGINX
