subscription_id     = ""
client_id           = ""
client_secret       = ""
tenant_id           = ""
resource_group_name = "1-34668c4e-playground-sandbox"
storage_account_name = ""
ssh_public_key      = ""