---
- name: Update Nginx configuration to change port 80 to S81
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '^\s*listen\s+80;'
    replace: '    listen {{ nginx_port }};'
  notify: Restart NGINX