name: Azure Infrastructure Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action (provision/destroy)'
        required: true
        default: 'provision'
        type: choice
        options:
          - provision
          - destroy

jobs:
  manage-infrastructure:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    # Navigate to Terraform Directory and Initialize
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init -backend-config="terraform.tfvars"

    # Terraform Apply or Destroy
    - name: Manage Infrastructure
      working-directory: ./terraform
      run: |
        if [ "${{ github.event.inputs.action }}" == "provision" ]; then
          terraform apply -auto-approve;
        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform destroy -auto-approve;
        fi

